"""
cuong_nhuoc.py — Phase 3a: Ngũ Hành Cường Nhược (Chart Strength Analysis).

Determines if the Day Master is strong (旺), weak (弱), or balanced.

Source of truth: docs/algorithm.md §21
"""

from __future__ import annotations

from engine.can_chi import CAN_HANH
from engine.hoa_hop import (
    apply_transformations_to_elements,
    detect_stem_transformations,
)
from engine.tang_can import get_all_elements, get_day_master_support, get_tang_can

# ─────────────────────────────────────────────────────────────────────────────
# Seasonal strength (Đắc Lệnh / 得令)
# Which element is "in season" based on month Dia Chi
# ─────────────────────────────────────────────────────────────────────────────

# Month chi → element that is strongest (đắc lệnh)
# Spring: Dần(2), Mão(3) → Mộc vượng; Thìn(4) = transition (Thổ)
# Summer: Tỵ(5), Ngọ(6) → Hỏa vượng; Mùi(7) = transition (Thổ)
# Autumn: Thân(8), Dậu(9) → Kim vượng; Tuất(10) = transition (Thổ)
# Winter: Hợi(11), Tý(0) → Thủy vượng; Sửu(1) = transition (Thổ)
SEASONAL_ELEMENT: dict[int, str] = {
    0:  "Thủy",  # Tý (winter)
    1:  "Thổ",   # Sửu (late winter transition)
    2:  "Mộc",   # Dần (spring)
    3:  "Mộc",   # Mão (spring)
    4:  "Thổ",   # Thìn (late spring transition)
    5:  "Hỏa",   # Tỵ (summer)
    6:  "Hỏa",   # Ngọ (summer)
    7:  "Thổ",   # Mùi (late summer transition)
    8:  "Kim",   # Thân (autumn)
    9:  "Kim",   # Dậu (autumn)
    10: "Thổ",   # Tuất (late autumn transition)
    11: "Thủy",  # Hợi (winter)
}

# Ngũ Hành Tương Sinh map: element → element it generates
SINH_MAP: dict[str, str] = {
    "Kim": "Thủy", "Mộc": "Hỏa", "Thủy": "Mộc",
    "Hỏa": "Thổ", "Thổ": "Kim",
}

# Reverse: element → element that generates it
SINH_BY_MAP: dict[str, str] = {v: k for k, v in SINH_MAP.items()}


def _is_in_season(day_master_hanh: str, month_chi_idx: int) -> bool:
    """Check if the Day Master's element is in season (đắc lệnh)."""
    return SEASONAL_ELEMENT[month_chi_idx] == day_master_hanh


def _seasonal_bonus(day_master_hanh: str, month_chi_idx: int) -> float:
    """
    Seasonal strength modifier.

    - In season (đắc lệnh): +2.0
    - Generated by seasonal element: +1.0
    - Same as seasonal element: +2.0
    - Destroyed by seasonal element: -1.0
    - Neutral: 0
    """
    seasonal = SEASONAL_ELEMENT[month_chi_idx]

    if seasonal == day_master_hanh:
        return 2.0
    # Seasonal element generates Day Master → support
    if SINH_MAP.get(seasonal) == day_master_hanh:
        return 1.0
    # Day Master generates seasonal element → drain
    if SINH_MAP.get(day_master_hanh) == seasonal:
        return -0.5
    # Seasonal element controls Day Master → opposition
    # (Kim khắc Mộc, Mộc khắc Thổ, etc.)
    KHAC_MAP = {
        "Kim": "Mộc", "Mộc": "Thổ", "Thổ": "Thủy",
        "Thủy": "Hỏa", "Hỏa": "Kim",
    }
    if KHAC_MAP.get(seasonal) == day_master_hanh:
        return -1.0
    return 0.0


def _has_root_in_branches(tu_tru: dict, target_hanh: str) -> bool:
    """Đắc địa — DM or Ấn element present as hidden stem (Chủ/Trung Khí)."""
    for pillar_key in ("year", "month", "day", "hour"):
        for hidden in get_tang_can(tu_tru[pillar_key]["chi_idx"]):
            if hidden["hanh"] == target_hanh and hidden["weight"] >= 0.6:
                return True
    return False


def _effective_stem_hanh_for_support(
    tu_tru: dict,
    pillar_key: str,
    transforms: list[dict],
) -> str:
    from engine.hoa_hop import effective_stem_hanh

    can_idx = tu_tru[pillar_key]["can_idx"]
    eff_hanh, transformed = effective_stem_hanh(pillar_key, can_idx, transforms)
    return eff_hanh if transformed else CAN_HANH[can_idx]


def _count_supporting_stems(
    tu_tru: dict,
    dm_hanh: str,
    transforms: list[dict],
) -> int:
    """Đắc thế — stems (year/month/hour) whose effective element supports DM."""
    parent = SINH_BY_MAP.get(dm_hanh)
    count = 0
    for pillar_key in ("year", "month", "hour"):
        stem_hanh = _effective_stem_hanh_for_support(tu_tru, pillar_key, transforms)
        if stem_hanh == dm_hanh or stem_hanh == parent:
            count += 1
    return count


def analyze_chart_strength(
    tu_tru: dict,
    transforms: list[dict] | None = None,
) -> dict:
    """
    Determine Day Master strength.

    Args:
        tu_tru: dict from get_tu_tru() with year/month/day/hour pillars
                plus nhat_chu

    Returns:
        dict with keys:
            strength: "vượng" | "nhược" | "cân bằng"
            element_counts: {element: weight}
            seasonal_element: str
            is_in_season: bool
            day_master_hanh: str
            day_master_support: float
            day_master_opposition: float
            support_ratio: float (0.0-1.0)
    """
    dm_hanh = tu_tru["nhat_chu"]["hanh"]
    month_chi_idx = tu_tru["month"]["chi_idx"]
    parent_hanh = SINH_BY_MAP[dm_hanh]

    # 1. Raw + effective element counts (after 合化)
    raw_element_counts = get_all_elements(tu_tru)
    stem_transformations = (
        transforms if transforms is not None else detect_stem_transformations(tu_tru)
    )
    element_counts = apply_transformations_to_elements(
        raw_element_counts, tu_tru, stem_transformations,
    )

    # 2. Support vs opposition from effective counts
    support = (
        element_counts.get(dm_hanh, 0.0) + element_counts.get(parent_hanh, 0.0)
    )
    total = sum(element_counts.values())
    opposition = total - support

    # 3. Đắc lệnh (seasonal) — affects strength tier / Dụng Thần / chọn ngày
    season_bonus = _seasonal_bonus(dm_hanh, month_chi_idx)
    support += max(0, season_bonus)
    opposition += max(0, -season_bonus)

    # Đắc địa / đắc thế: boolean facts for LLM only — must NOT shift strength
    # tier on borderline charts (regression: day-detail personalized score parity).
    dac_lenh = _is_in_season(dm_hanh, month_chi_idx)
    dac_dia = _has_root_in_branches(tu_tru, dm_hanh) or _has_root_in_branches(
        tu_tru, parent_hanh,
    )
    dac_the_count = _count_supporting_stems(tu_tru, dm_hanh, stem_transformations)

    # 4. Calculate support ratio
    total_adj = support + opposition
    support_ratio = support / total_adj if total_adj > 0 else 0.5

    # 5. Determine strength
    if support_ratio >= 0.55:
        strength = "vượng"
    elif support_ratio <= 0.40:
        strength = "nhược"
    else:
        strength = "cân bằng"

    return {
        "strength": strength,
        "element_counts": element_counts,
        "raw_element_counts": raw_element_counts,
        "stem_transformations": stem_transformations,
        "seasonal_element": SEASONAL_ELEMENT[month_chi_idx],
        "is_in_season": dac_lenh,
        "dac_lenh": dac_lenh,
        "dac_dia": dac_dia,
        "dac_the": dac_the_count >= 2,
        "dac_the_count": dac_the_count,
        "day_master_hanh": dm_hanh,
        "day_master_support": round(support, 2),
        "day_master_opposition": round(opposition, 2),
        "support_ratio": round(support_ratio, 3),
    }
